version: '3'

services:
 project-two:
  build: .
  image: maicommr/laravel8
  container_name: project2
  volumes:
   - .:/var/www
  networks:
   - app-network
  depends_on:
   - db
   - redis
  entrypoint: "dockerize -template ./docker_config/app/.env:.env -wait tcp://db:3306 -timeout 30s ./docker_config/entrypoint.sh"
  environment:
   - DB_HOST=db
   - DB_PORT=3306
   - DB_DATABASE=laravel
   - DB_USERNAME=root
   - DB_PASSWORD=root

 nginx:
  build: docker_config/nginx
  container_name: project2-nginx
  entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off";
  environment:
   - APP_NAME=project-two
   - APP_PORT=9000
  restart: always
  tty: true
  ports:
   - "6969:80"
  volumes:
   - .:/var/www
  networks:
   - app-network
  depends_on:
   - project-two
  # entrypoint: dockerize -template ./docker_config/nginx/nginx.conf:/etc/nginx/conf.d



 redis:
  image: redis:alpine
  container_name: project2-redis
  expose:
   - 6379
  networks:
    - app-network

 db:
  image: mysql:5.7
  command: --innodb-use-native-aio=0
  container_name: project2-database
  restart: always
  tty: true
  ports:
   - "3401:3306"
  environment:
   - MYSQL_DATABASE=laravel
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=root
  networks:
   - app-network
  volumes:
   - ./docker_config/dbdata:/var/lib/mysql

networks:
 app-network:
  driver: bridge






